export enum Actions_Type {
   //accountPageReducer
   ADD_POST = 'ADD-POST',
   CHANGE_VALUE_TEXTAREA = 'CHANGE-VALUE-TEXTAREA',
   GET_PROFILE = 'GET-PROFILE',

   //communicationPageReducer
   ADD_MESSAGE = 'ADD-MESSAGE',
   CHANGE_VALUE_MESSAGE = 'CHANGE-VALUE-MESSAGE',

   //users-page-reducer
   CHANGE_FOLLOW_USER = 'CHANGE-FOLLOW-USER',
   SET_USERS = 'SET_USERS',
   SET_TOTAL_COUNT = 'SET-TOTAL-COUNT',
   CHANGE_PAGINATION = 'CHANGE-PAGINATION',
   CHANGE_IS_PRELOADER = 'CHANGE-IS-PRELOADER',
   CHANGE_IS_DISABLED = 'CHANGE-IS-DISABLED',

   //auth-api-reducer
   SET_AUTH_DATA = 'SET-AUTH-DATA',
}
