export enum Actions_Type {
   //accountPageReducer
   ADD_POST = 'ADD-POST',
   CHANGE_VALUE_TEXTAREA = 'CHANGE-VALUE-TEXTAREA',
   GET_PROFILE = 'GET-PROFILE',
   CHANGE_ID = 'CHANGE-ID',

   //communicationPageReducer
   ADD_VALUE_MESSAGE = 'ADD-VALUE-MESSAGE',
   CHANGE_VALUE_MESSAGE = 'CHANGE-VALUE-MESSAGE',

   //usersPageReducer
   CHANGE_FOLLOW_USER = 'CHANGE-FOLLOW-USER',
   GET_USERS = 'GET_USERS',
   GET_TOTAL_COUNT = 'GET-TOTAL-COUNT',
   CHANGE_PAGINATION = 'CHANGE-PAGINATION',
   CHANGE_IS_PRELOADER = 'CHANGE-IS-PRELOADER',
   CHANGE_IS_DISABLED = 'CHANGE-IS-DISABLED',

   //auth-reducer
   CHANGE_AUTH_DATA = 'CHANGE-AUTH-DATA',
}
