export enum Actions_Type {
   //accountReducer
   ADD_POST = 'ADD-POST',
   CHANGE_VALUE_TEXTAREA = 'CHANGE-VALUE-TEXTAREA',
   GET_PROFILE = 'GET-PROFILE',
   GET_STATUS = 'GET-STATUS',
   UPDATE_STATUS = 'UPDATE-STATUS',

   //communicationReducer
   ADD_MESSAGE = 'ADD-MESSAGE',

   //users
   CHANGE_FOLLOW_USER = 'CHANGE-FOLLOW-USER',
   SET_USERS = 'SET_USERS',
   SET_TOTAL_COUNT = 'SET-TOTAL-COUNT',
   CHANGE_PAGINATION = 'CHANGE-PAGINATION',
   CHANGE_IS_PRELOADER = 'CHANGE-IS-PRELOADER',
   CHANGE_IS_DISABLED = 'CHANGE-IS-DISABLED',

   //auth
   SET_AUTH_DATA = 'SET-AUTH-DATA',
   UPDATE_AUTH_DATA = 'UPDATE-AUTH-DATA',
   LOGOUT_AUTH_DATA = 'LOGOUT-AUTH-DATA'
}
